version: "3.9"

services:
  app:
    image: ghcr.io/gabriellyzup/container:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cadastro_clientes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    command: ["--tls-verify=false"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cadastro_clientes
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: